import { TestBed } from '@angular/core/testing';
import { vi, describe, it, expect, beforeEach } from 'vitest';
import { DndService } from './dnd.service';
import { FormSchemaService } from './form-schema.service';
import { BuilderRegistryService } from '../registry/builder-registry.service';
import { KeyGeneratorService } from './key-generator.service';
import { BuilderStateService } from './builder-state.service';
import { BUILDER_COMPONENTS } from '../tokens/builder-components.token';
import { BUILDER_CONFIG } from '../tokens/builder-config.token';
import { monitorForElements } from '@atlaskit/pragmatic-drag-and-drop/element/adapter';

// Mock the pragmatic DND module
vi.mock('@atlaskit/pragmatic-drag-and-drop/element/adapter', () => ({
  monitorForElements: vi.fn(() => {
    return () => {}; // return cleanup function
  })
}));

describe('DndService', () => {
  let service: DndService;
  let formSchemaService: FormSchemaService;
  let stateService: BuilderStateService;
  
  beforeEach(() => {
    vi.clearAllMocks();

    TestBed.configureTestingModule({
      providers: [
        DndService,
        FormSchemaService,
        BuilderRegistryService,
        KeyGeneratorService,
        BuilderStateService,
        {
          provide: BUILDER_CONFIG,
          useValue: { historyDebounceMs: 100, maxHistorySize: 10, allowCustomJs: false, groupOrder: [] }
        },
        {
          provide: BUILDER_COMPONENTS,
          useValue: [
            {
              type: 'text-input',
              label: 'Text Input',
              category: 'basic',
              icon: 'text',
              defaultSchema: { type: 'text-input', label: 'Default Text' }
            },
            {
              type: 'button',
              label: 'Button Label',
              category: 'basic',
              icon: 'button',
              defaultSchema: { type: 'button' }
            }
          ]
        }
      ]
    });

    service = TestBed.inject(DndService);
    formSchemaService = TestBed.inject(FormSchemaService);
    stateService = TestBed.inject(BuilderStateService);
  });

  it('should initialize and register monitorForElements', () => {
    service.init();
    expect(monitorForElements).toHaveBeenCalledOnce();
    
    // Calling init again shouldn't re-register
    service.init();
    expect(monitorForElements).toHaveBeenCalledOnce();
  });

  it('should cleanup on destroy', () => {
    const cleanupMock = vi.fn();
    vi.mocked(monitorForElements).mockReturnValueOnce(cleanupMock);
    
    service.init();
    service.ngOnDestroy();
    
    expect(cleanupMock).toHaveBeenCalledOnce();
  });

  describe('DND Events', () => {
    let dndConfig: any;

    beforeEach(() => {
      service.init();
      dndConfig = vi.mocked(monitorForElements).mock.calls[0][0];
    });

    it('should set dragging state on drag start', () => {
      dndConfig.onDragStart();
      expect(stateService.isDragging()).toBe(true);
    });

    it('should reset dragging state and do nothing if dropped outside', () => {
      stateService.setDragging(true);
      dndConfig.onDrop({
        source: { data: { source: 'palette', descriptorType: 'text-input', builderId: stateService.builderId } },
        location: { current: { dropTargets: [] } }
      });
      
      expect(stateService.isDragging()).toBe(false);
      expect(formSchemaService.schema().components.length).toBe(0);
    });

    it('should do nothing if drop target data is invalid', () => {
      dndConfig.onDrop({
        source: { data: { source: 'palette', descriptorType: 'text-input', builderId: stateService.builderId } },
        location: { current: { dropTargets: [{ data: { invalid: true } }] } }
      });
      expect(formSchemaService.schema().components.length).toBe(0);
    });

    it('should add a component when dropped from palette', () => {
      dndConfig.onDrop({
        source: { data: { source: 'palette', descriptorType: 'text-input', builderId: stateService.builderId } },
        location: { current: { dropTargets: [{ data: { parentId: null, index: 0, builderId: stateService.builderId } }] } }
      });
      
      const components = formSchemaService.schema().components;
      expect(components.length).toBe(1);
      expect(components[0].type).toBe('text-input');
      expect(components[0].key).toBe('textInput'); // Generated by keyGen
      expect(components[0].label).toBe('Default Text'); // Prioritize defaultSchema.label
      
      // Should also set active node
      expect(stateService.activeNodeId()).toBe(components[0].id);
    });

    it('should fall back to descriptor label if defaultSchema lacks a label', () => {
      dndConfig.onDrop({
        source: { data: { source: 'palette', descriptorType: 'button', builderId: stateService.builderId } },
        location: { current: { dropTargets: [{ data: { parentId: null, index: 0, builderId: stateService.builderId } }] } }
      });
      
      const components = formSchemaService.schema().components;
      expect(components.length).toBe(1);
      expect(components[0].label).toBe('Button Label'); // Fallback to descriptor.label
    });

    it('should do nothing if dropped from palette with unknown descriptor', () => {
      dndConfig.onDrop({
        source: { data: { source: 'palette', descriptorType: 'unknown', builderId: stateService.builderId } },
        location: { current: { dropTargets: [{ data: { parentId: null, index: 0, builderId: stateService.builderId } }] } }
      });
      
      expect(formSchemaService.schema().components.length).toBe(0);
    });

    it('should move a component when dropped from canvas', () => {
      // First, add a component manually
      formSchemaService.addComponent(null, 0, { id: 'c1', type: 'text-input', label: 'C1' });
      formSchemaService.addComponent(null, 1, { id: 'c2', type: 'text-input', label: 'C2' });
      
      dndConfig.onDrop({
        source: { data: { source: 'canvas', nodeId: 'c1', builderId: stateService.builderId } },
        location: { current: { dropTargets: [{ data: { parentId: null, index: 2, builderId: stateService.builderId } }] } }
      });
      
      const components = formSchemaService.schema().components;
      expect(components[0].id).toBe('c2');
      expect(components[1].id).toBe('c1');
    });
  });
});
