import type { ComponentDescriptor } from '../types/component-descriptor';

import { TEXT_INPUT_DESCRIPTOR, EMAIL_DESCRIPTOR, PASSWORD_DESCRIPTOR, TEL_DESCRIPTOR } from './text-inputs.descriptor';
import { NUMBER_DESCRIPTOR, TEXTAREA_DESCRIPTOR } from './number-textarea.descriptor';
import { SELECT_DESCRIPTOR, COMBOBOX_DESCRIPTOR, CHECKBOX_DESCRIPTOR, RADIO_DESCRIPTOR, CHECKBOX_GROUP_DESCRIPTOR, RADIO_GROUP_DESCRIPTOR } from './selection.descriptor';
import { DATE_DESCRIPTOR, TIME_DESCRIPTOR, DATETIME_LOCAL_DESCRIPTOR } from './date-time.descriptor';
import { HIDDEN_DESCRIPTOR, CONTENT_DESCRIPTOR, DIVIDER_DESCRIPTOR, BUTTON_DESCRIPTOR, SUBMIT_DESCRIPTOR } from './utility.descriptor';
import { PANEL_DESCRIPTOR, COLUMNS_DESCRIPTOR, TABS_DESCRIPTOR, FIELDSET_DESCRIPTOR, REPEATER_DESCRIPTOR } from './layout.descriptor';

export {
  TEXT_INPUT_DESCRIPTOR,
  EMAIL_DESCRIPTOR,
  PASSWORD_DESCRIPTOR,
  TEL_DESCRIPTOR,
  NUMBER_DESCRIPTOR,
  TEXTAREA_DESCRIPTOR,
  SELECT_DESCRIPTOR,
  COMBOBOX_DESCRIPTOR,
  CHECKBOX_DESCRIPTOR,
  RADIO_DESCRIPTOR,
  CHECKBOX_GROUP_DESCRIPTOR,
  RADIO_GROUP_DESCRIPTOR,
  DATE_DESCRIPTOR,
  TIME_DESCRIPTOR,
  DATETIME_LOCAL_DESCRIPTOR,
  HIDDEN_DESCRIPTOR,
  CONTENT_DESCRIPTOR,
  DIVIDER_DESCRIPTOR,
  BUTTON_DESCRIPTOR,
  SUBMIT_DESCRIPTOR,
  PANEL_DESCRIPTOR,
  COLUMNS_DESCRIPTOR,
  TABS_DESCRIPTOR,
  FIELDSET_DESCRIPTOR,
  REPEATER_DESCRIPTOR
};

/**
 * All 23 built-in component descriptors.
 * Can be provided via the BUILDER_COMPONENTS InjectionToken.
 */
export const BUILT_IN_BUILDER_COMPONENTS: ComponentDescriptor[] = [
  // Basic
  TEXT_INPUT_DESCRIPTOR,
  EMAIL_DESCRIPTOR,
  PASSWORD_DESCRIPTOR,
  TEL_DESCRIPTOR,
  NUMBER_DESCRIPTOR,
  TEXTAREA_DESCRIPTOR,
  SELECT_DESCRIPTOR,
  COMBOBOX_DESCRIPTOR,
  CHECKBOX_DESCRIPTOR,
  RADIO_DESCRIPTOR,

  // Advanced
  CHECKBOX_GROUP_DESCRIPTOR,
  RADIO_GROUP_DESCRIPTOR,
  DATE_DESCRIPTOR,
  TIME_DESCRIPTOR,
  DATETIME_LOCAL_DESCRIPTOR,
  HIDDEN_DESCRIPTOR,
  CONTENT_DESCRIPTOR,
  DIVIDER_DESCRIPTOR,
  BUTTON_DESCRIPTOR,
  SUBMIT_DESCRIPTOR,

  // Layout
  PANEL_DESCRIPTOR,
  COLUMNS_DESCRIPTOR,
  TABS_DESCRIPTOR,
  FIELDSET_DESCRIPTOR,
  REPEATER_DESCRIPTOR,
];
